flask/api/models/fate.py
from setup import db
from calculations.fate import Fate


class Fate(db.Model):
    __tablename__ = 'fates'
    id = db.Column(db.Integer, primary_key=True)
    mission_id = db.Column(db.Integer, db.ForeignKey('missions.id'))
    name = db.Column(db.String(50), nullable=False)
    pam_id = db.Column(db.Integer, nullable=False)
    unit = db.Column(db.String(50), nullable=False)
    fate = db.Column(db.Enum(Fate), nullable=False)
    fate_detail = db.Column(db.Enum(Fate), nullable=True)
    health = db.Column(db.String(50), nullable=False)
    wound = db.Column(db.Float, nullable=True)
    aircraft_status = db.Column(db.String(50), nullable=False)
    damage = db.Column(db.Float, nullable=True)
    takeoff_position_x = db.Column(db.Float, nullable=True)
    takeoff_position_z = db.Column(db.Float, nullable=True)
    landed_position_x = db.Column(db.Float, nullable=True)
    landed_position_z = db.Column(db.Float, nullable=True)
    ditched_position_x = db.Column(db.Float, nullable=True)
    ditched_position_z = db.Column(db.Float, nullable=True)
    crashed_position_x = db.Column(db.Float, nullable=True)
    crashed_position_z = db.Column(db.Float, nullable=True)
    bailout_position_x = db.Column(db.Float, nullable=True)
    bailout_position_z = db.Column(db.Float, nullable=True)
    start_position_x = db.Column(db.Float, nullable=True)
    start_position_z = db.Column(db.Float, nullable=True)
    target_position_x = db.Column(db.Float, nullable=True)
    target_position_z = db.Column(db.Float, nullable=True)
    captured_position_x = db.Column(db.Float, nullable=True)
    captured_position_z = db.Column(db.Float, nullable=True)
    dead_position_x = db.Column(db.Float, nullable=True)
    dead_position_z = db.Column(db.Float, nullable=True)

    def __repr__(self):
        return '<Fate %r>' % self.id

flask/api/models/mission.py
from setup import db


class Mission(db.Model):
    __tablename__ = 'missions'
    id = db.Column(db.Integer, primary_key=True)
    pam_campaign_id = db.Column(db.Integer, nullable=True)
    pam_id = db.Column(db.Integer, nullable=False)
    pam_name = db.Column(db.String(50), nullable=False)
    il2stats_id = db.Column(db.Integer, unique=True, nullable=False)
    filename = db.Column(db.String(50), nullable=False)
    frontline_red = db.Column(db.Text)
    frontline_blue = db.Column(db.Text)
    processed = db.Column(db.Boolean, nullable=False)

    def __repr__(self):
        return '<Mission %r>' % self.id

flask/api/models/wrap_up.py
from setup import db


class Wrap_Up(db.Model):
    __tablename__ = 'wrap_ups'
    id = db.Column(db.Integer, primary_key=True)
    mission_id = db.Column(
        db.Integer,
        db.ForeignKey('missions.id'),
        nullable=False)
    base_unit_name = db.Column(db.Text, nullable=False)
    sorties = db.Column(db.Integer)
    pilotHealthy = db.Column(db.Integer)
    pilotWounded = db.Column(db.Integer)
    pilotDead = db.Column(db.Integer)
    aircraftUnharmed = db.Column(db.Integer)
    aircraftDamaged = db.Column(db.Integer)
    aircraftDestroyed = db.Column(db.Integer)
    pilotLossPercentage = db.Column(db.Integer)
    aircraftLossPercentage = db.Column(db.Integer)

    def __repr__(self):
        return '<Wrap_Up %r>' % self.id

flask/api/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from setup import db
from werkzeug.security import generate_password_hash, check_password_hash
from models.user import User
from flask_login import login_user, login_required, logout_user

auth_blueprint = Blueprint('auth', __name__)


@auth_blueprint.route('/login')
def login():
    return render_template('login.html')


@auth_blueprint.route('/login', methods=['POST'])
def login_post():
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed
    # password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        # if the user doesn't exist or password is wrong, reload the page
        return redirect(url_for('auth.login'))

    # if the above check passes, then we know the user has the right
    # credentials
    login_user(user, remember=remember)
    return redirect(url_for('profile.profile'))


@auth_blueprint.route('/signup')
def signup():
    return render_template('signup.html')


@auth_blueprint.route('/signup', methods=['POST'])
def signup_post():
    # code to validate and add user to database goes here
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    # if this returns a user, then the email already exists in database
    user = User.query.filter_by(email=email).first()

    if user:  # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create a new user with the form data. Hash the password so the plaintext
    # version isn't saved.
    new_user = User(
        email=email,
        name=name,
        password=generate_password_hash(
            password,
            method='sha256'),
        admin=False,
        campaign_team=False,
        staff=False)

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index.index'))

flask/api/routes/fates.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user

fates_blueprint = Blueprint(name='fates', import_name=__name__)


@fates_blueprint.route("/fates", methods=['POST', 'GET'])
@login_required
def fates():
    if (current_user.staff is True) or (current_user.campaign_team is True):
        from models.fate import Fate
        from models.mission import Mission
        from routes.index import get_processed_missions

        mission_id = request.form.get('mission_id')
        fates = Fate.query.filter_by(
            mission_id=mission_id).order_by(
            Fate.unit).order_by(
            Fate.name).all()

        mission = Mission.query.filter_by(id=mission_id).first()

        if request.method == "POST":
            flash("Fates for mission: " + mission.pam_name)

        return render_template('fates.html',
                               processed_missions=get_processed_missions(),
                               fates=fates)
    else:
        flash('You do not have the permissions to access this page.')
        return redirect(url_for('index.index'))

flask/api/routes/pilots_not_linked.py
from flask import Blueprint, render_template, redirect, url_for, flash
from json import load
from flask_login import login_required, current_user

pilots_not_linked_blueprint = Blueprint(
    name='pilots_not_linked', import_name=__name__)


@pilots_not_linked_blueprint.route("/pilots_not_linked")
@login_required
def fates():
    if current_user.staff is True:
        pam_pilots_and_box_id = get_pam_pilots_and_box_id()
        il2stats_pilots_and_box_id = get_il2stats_pilots_and_box_id()

        pilots_not_linked = get_pilots_not_linked(
            pam_pilots_and_box_id, il2stats_pilots_and_box_id)

        return render_template(
            'pilots_not_linked.html',
            pilots_not_linked=pilots_not_linked)
    else:
        flash('You do not have the permissions to access this page.')
        return redirect(url_for('index.index'))


def get_pam_pilots_and_box_id():
    from calculations.pam import Pam
    from calculations.utils import Utils

    utils = Utils(False, False, False)

    try:
        with open("../configs/secret.json", "r") as json_file:
            secrets = load(json_file)

        PAM_user = secrets["PAM_user"]
        PAM_password = secrets["PAM_password"]
        PAM_host = secrets["PAM_host"]
        PAM_database = secrets["PAM_database"]

    except FileNotFoundError as err:

        utils.errorPrint(err)
        utils.fatalError("Config read-out failed")

    pam = Pam(PAM_host, PAM_user, PAM_password, PAM_database, utils)
    pam.createConnection()

    query = (
        "SELECT id AS pam_id, callsign AS pam_callsign, boxid AS pam_boxid FROM member;")
    query_return = pam.query(query)

    pam_pilots_and_box_id = []
    for (pam_id, pam_callsign, pam_boxid) in query_return:
        pam_pilots_and_box_id.append({"pam_id": pam_id,
                                      "pam_callsign": pam_callsign,
                                      "pam_boxid": pam_boxid,
                                      "is_in_il2stats": False})

    pam.closeConnection()

    return pam_pilots_and_box_id


def get_il2stats_pilots_and_box_id():
    from calculations.il2_stats import Il2_stats
    from calculations.utils import Utils

    utils = Utils(False, False, False)

    try:
        with open("../configs/secret.json", "r") as json_file:
            secrets = load(json_file)

        IL2stats_user = secrets["IL2stats_user"]
        IL2stats_password = secrets["IL2stats_password"]
        IL2stats_host = secrets["IL2stats_host"]
        IL2stats_database = secrets["IL2stats_database"]

    except FileNotFoundError as err:

        utils.errorPrint(err)
        utils.fatalError("Config read-out failed")

    il2_stats = Il2_stats(
        IL2stats_host,
        IL2stats_user,
        IL2stats_password,
        IL2stats_database,
        utils)
    il2_stats.createConnection()

    query = (
        "SELECT nickname AS il2stats_nickname, uuid AS il2stats_boxid FROM profiles;")
    query_return = il2_stats.query(query)

    il2stats_pilots_and_box_id = []
    for (il2stats_nickname, il2stats_boxid) in query_return:
        il2stats_pilots_and_box_id.append(
            {"il2stats_nickname": il2stats_nickname, "il2stats_boxid": il2stats_boxid, "is_in_pam": False})

    il2_stats.closeConnection()

    return il2stats_pilots_and_box_id


def get_pilots_not_linked(pilot_list_pam, pilot_list_il2stats):
    for pam_pilot in pilot_list_pam:
        for pilot_il2stats in pilot_list_il2stats:
            if pam_pilot["pam_boxid"] == pilot_il2stats["il2stats_boxid"]:
                pam_pilot["is_in_il2stats"] = True
                pilot_il2stats["is_in_pam"] = True

    pilots_not_linked = []

    for pam_pilot in pilot_list_pam:
        if pam_pilot["is_in_il2stats"] is False:
            pilots_not_linked.append(pam_pilot)

    for pilot_il2stats in pilot_list_il2stats:
        if pilot_il2stats["is_in_pam"] is False:
            pilots_not_linked.append(pilot_il2stats)

    return pilots_not_linked

flask/api/routes/profile.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

profile_blueprint = Blueprint('profile', __name__)


@profile_blueprint.route('/profile')
@login_required
def profile():
    return render_template(
        'profile.html',
        name=current_user.name,
        admin=current_user.admin,
        campaign_team=current_user.campaign_team,
        staff=current_user.staff)

flask/api/routes/readme.py
from flask import Blueprint
from flask_login import login_required
from markdown import markdown

readme_blueprint = Blueprint('readme', __name__)


@readme_blueprint.route('/readme')
@login_required
def readme():
    try:
        with open("../README.md", "r") as readme_file:
            readme_string = markdown(readme_file.read())

    except FileNotFoundError as err:
        from calculations.utils import Utils
        utils = Utils(False, False, False)
        utils.errorPrint(err)
        utils.fatalError("Config read-out failed")

    return readme_string

flask/api/routes/wrap_up.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user


wrap_up_blueprint = Blueprint(name='wrap_up', import_name=__name__)


@wrap_up_blueprint.route('/wrap_up', methods=['POST', 'GET'])
@login_required
def wrap_up():
    if current_user.campaign_team is True:
        from models.wrap_up import Wrap_Up
        from models.mission import Mission
        from routes.index import get_processed_missions

        mission_id = request.form.get('mission_id')
        wrap_ups = Wrap_Up.query.filter_by(mission_id=mission_id).all()

        mission = Mission.query.filter_by(id=mission_id).first()

        if request.method == "POST":
            flash("Wrap up for mission: " + mission.pam_name)

        return render_template(
            'wrap_up.html',
            processed_missions=get_processed_missions(),
            wrap_ups=wrap_ups)
    else:
        flash('You do not have the permissions to access this page.')
        return redirect(url_for('index.index'))

flask/templates/admin.html
{% extends 'base.html' %}

{% block head %}

<title>FTC Check-Your-Can - Admin section</title>

{% endblock %}


{% block body %}

<h2>Users</h2>

<table>
   <thead>
      <tr>
         <th>id</th>
         <th>email</th>
         <th>name</th>
         <th>admin</th>
         <th>campaign_team</th>
         <th>staff</th>
      </tr>
   </thead>
   
   <tbody>
      {% for user in users %}
         <form action="/admin_user" method="POST">
            <tr>
               <td>{{ user.id }}</td>
               <td>{{ user.email }}</td>
               <td>{{ user.name }}</td>
               <td>{{ user.admin }}</td>
               <td>{{ user.campaign_team }}</td>
               <td>{{ user.staff }}</td>
            </tr>
         </form>
      {% endfor %}
   </tbody>
</table>

{% endblock %}

flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %}{% endblock %}
</head>
<body background="">
    <div class="navbar-end">
        <a href="{{ url_for('index.index') }}" class="navbar-item">
            Home
        </a>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('profile.profile') }}" class="navbar-item">
            Profile
        </a>
        {% endif %}
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('auth.login') }}" class="navbar-item">
            Login
        </a>
        <a href="{{ url_for('auth.signup') }}" class="navbar-item">
            Sign Up
        </a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
            Logout
        </a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('readme.readme') }}" class="navbar-item">
            README
        </a>
        {% endif %}
    </div>
    {% block body %}{% endblock %}
</body>
</html>

flask/templates/fates.html
{% extends 'base.html' %}

{% block head %}

<title>FTC Check-Your-Fate - Fates from DB</title>

{% endblock %}


{% block body %}
<div class="form">
    <form action="/fates" method="POST">
        <select name="mission_id" method="GET" action="/get_processed_missions" id="mission_id">
            {% for processed_mission in processed_missions %}
                <option value="{{processed_mission.id}}">{{processed_mission.pam_name}}</option>
            {% endfor %}
        </select><br>
        <input type="submit" value="View fates">
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
   <div class="notification is-danger">
       {{ messages[0] }}
   </div>
{% endif %}
{% endwith %}

<table>
   <thead>
      <tr>
         <th>id</th>
         <th>recalc</th>
         <th>mission_id</th>
         <th>pam_id</th>
         <th>name</th>
         <th>unit</th>
         <th>fate</th>
         <th>fate_detail</th>
         <th>health</th>
         <th>wound</th>
         <th>aircraft_status</th>
         <th>damage</th>
         <th>takeoff_position_x</th>
         <th>takeoff_position_z</th>
         <th>landed_position_x</th>
         <th>landed_position_z</th>
         <th>ditched_position_x</th>
         <th>ditched_position_z</th>
         <th>bailout_position_x</th>
         <th>bailout_position_z</th>
         <th>crashed_position_x</th>
         <th>crashed_position_z</th>
         <th>target_position_x</th>
         <th>target_position_z</th>
         <th>captured_position_x</th>
         <th>captured_position_z</th>
         <th>dead_position_x</th>
         <th>dead_position_z</th>
      </tr>
   </thead>
   
   <tbody>
      {% for fate in fates %}
         <tr>
            <td>{{ fate.id }}</td>
            <td>
                <div class="form">
                    <form action="/recalc" method="POST">
                        <input type="submit" name="fate_id" value={{fate.id}}>
                    </form>
                </div>
            </td>
            <td>{{ fate.mission_id }}</td>
            <td>{{ fate.pam_id }}</td>
            <td>{{ fate.name }}</td>
            <td>{{ fate.unit }}</td>
            <td>{{ fate.fate }}</td>
            <td>{{ fate.fate_detail }}</td>
            <td>{{ fate.health }}</td>
            <td>{{ fate.wound }}</td>
            <td>{{ fate.aircraft_status }}</td>
            <td>{{ fate.damage }}</td>
            <td>{{ fate.takeoff_position_x }}</td>
            <td>{{ fate.takeoff_position_z }}</td>
            <td>{{ fate.landed_position_x }}</td>
            <td>{{ fate.landed_position_z }}</td>
            <td>{{ fate.ditched_position_x }}</td>
            <td>{{ fate.ditched_position_z }}</td>
            <td>{{ fate.bailout_position_x }}</td>
            <td>{{ fate.bailout_position_z }}</td>
            <td>{{ fate.crashed_position_x }}</td>
            <td>{{ fate.crashed_position_z }}</td>
            <td>{{ fate.target_position_x }}</td>
            <td>{{ fate.target_position_z }}</td>
            <td>{{ fate.captured_position_x }}</td>
            <td>{{ fate.captured_position_z }}</td>
            <td>{{ fate.dead_position_x }}</td>
            <td>{{ fate.dead_position_z }}</td>
         </tr>
      {% endfor %}
   </tbody>
</table>

{% endblock %}

flask/templates/index.html
{% extends 'base.html' %}

{% block head %}
<style>
    body {
    background-image: url("https://cdn.discordapp.com/attachments/903029574084997180/903725085007937626/20180408232614_1.jpg");
    background-repeat: no-repeat;
    background-color: #cccccc;
    }
</style>


<title>FTC Check-Your-Can</title>

{% endblock %}


{% block body %}

{% with messages = get_flashed_messages() %}
{% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
{% endif %}
{% endwith %}

<h1>FTC Check-Your-Can</h1>
<p align="left">
    {% if current_user.is_authenticated %}
    <div class="form">
        <form action="/map" method="POST" target="_blank">
            <select name="pam_mission_id" method="GET" action="/get_processed_missions" id="pam_mission_id">
                {% for processed_mission in processed_missions %}
                    <option value="{{processed_mission.pam_id}}">{{processed_mission.pam_name}}</option>
                {% endfor %}
            </select><br>
            <input type="submit" value="View Map">
        </form>
    </div>
    <br>
    <a href=wrap_up>
        <button class=grey style="height:75px;width:150px">
            Wrap Up
        </button>
    </a>
    <br>
    <a href=manage_mission>
        <button class=grey style="height:75px;width:150px">
            Manage missions
        </button>
    </a>
    <br>
    <a href=fates>
        <button class=grey style="height:75px;width:150px">
            Fates
        </button>
    </a>
    <br>
    <a href=pilots_not_linked>
        <button class=grey style="height:75px;width:150px">
            Pilots not linked
        </button>
    </a>
    <br>
    <a href=admin>
        <button class=grey style="height:75px;width:150px">
            Admin section
        </button>
    </a>
    {% endif %}
</p>

{% endblock %}

flask/templates/login.html
{% extends "base.html" %}

{% block head %}

<title>FTC Check-Your-Can Login</title>

{% endblock %}

{% block body %}
<div class="column is-4 is-offset-4">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
    {% endif %}
    {% endwith %}
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

flask/templates/missions.html
{% extends 'base.html' %}

{% block head %}

<title>FTC Check-Your-Can - Missions from DB</title>

{% endblock %}


{% block body %}

<br>
<a href=process_mission>
    <button class=grey style="height:75px;width:150px">
        Process missions
    </button>
</a>

{% with messages = get_flashed_messages() %}
{% if messages %}
   <div class="notification">
       {{ messages[0] }}.
   </div>
{% endif %}
{% endwith %}

<div class="form">
    <form action = "upload_mission" method = "POST" 
        enctype = "multipart/form-data">
        <input type = "file" name = "file" />
        <input type = "submit"/>
    </form>
</div>

<div class="form">
    <form action="/manage_mission" method="POST">
        <label for="pam_missions_on_debriefing">Select the proper PAM Mission on debriefing</label><br>
        <select name="pam_missions_on_debriefing" method="GET" id="pam_missions_on_debriefing">
            {% for pam_mission_on_debriefing in pam_missions_on_debriefing %}
                <option value="{{pam_mission_on_debriefing}}">{{pam_mission_on_debriefing['pam_name']}}</option>
            {% endfor %}
        </select><br>

        <label for="il2stats_id">Select the proper il2_stats Mission which is not yet linked</label><br>
        <select name="il2stats_missions_not_linked" method="GET" id="il2stats_missions_not_linked">
            {% for il2stats_mission_not_linked in il2stats_missions_not_linked %}
                <option value="{{il2stats_mission_not_linked}}">{{il2stats_mission_not_linked['il2stats_name']}}</option>
            {% endfor %}
        </select><br>

        <label for="filename">Select the proper uploaded *.mission file</label><br>
        <select name="missionfiles" method="GET" id="filename">
            {% for missionfile in missionfiles %}
                <option value="{{missionfile}}">{{missionfile}}</option>
            {% endfor %}
        </select><br>

        <label for="submit">Check your inputs before adding the mission!</label><br>
        <input type="submit" value="Add Mission">
    </form>
</div>

<table>
   <thead>
      <tr>
         <th>id</th>
         <th>pam_campaign_id</th>
         <th>pam_id</th>
         <th>pam_name</th>
         <th>il2stats_id</th>
         <th>filename</th>
         <th>processed</th>
         <th>delete</th>
      </tr>
   </thead>
   
   <tbody>
      {% for mission in missions %}
         <tr>
            <td>{{ mission.id }}</td>
            <td>{{ mission.pam_campaign_id }}</td>
            <td>{{ mission.pam_id }}</td>
            <td>{{ mission.pam_name }}</td>
            <td>{{ mission.il2stats_id }}</td>
            <td>{{ mission.filename }}</td>
            <td>{{ mission.processed }}</td>
            <td>
                <div class="form">
                    <form action="/delete_mission" method="POST">
                        <input type="submit" name="mission_id" value={{mission.id}}>
                    </form>
                </div>
            </td>
         </tr>
      {% endfor %}
   </tbody>
</table>

{% endblock %}

flask/templates/pilots_not_linked.html
{% extends 'base.html' %}

{% block head %}

<title>FTC Check-Your-Can - Pilots not linked</title>

{% endblock %}


{% block body %}

<table>
   <thead>
      <tr>
         <th>pam_id</th>
         <th>pam_callsign</th>
         <th>pam_boxid</th>
         <th>il2stats_nickname</th>
         <th>Jason-DNA (il2stats_boxid)</th>
      </tr>
   </thead>
   
   <tbody>
      {% for pilot_not_linked in pilots_not_linked %}
         <tr>
            <td>{{ pilot_not_linked["pam_id"] }}</td>
            <td>{{ pilot_not_linked["pam_callsign"] }}</td>
            <td>{{ pilot_not_linked["pam_boxid"] }}</td>
            <td>{{ pilot_not_linked["il2stats_nickname"] }}</td>
            <td>{{ pilot_not_linked["il2stats_boxid"] }}</td>
         </tr>
      {% endfor %}
   </tbody>
</table>

{% endblock %}

flask/templates/profile.html
{% extends "base.html" %}

{% block head %}

<title>FTC Check-Your-Can Signup</title>

{% endblock %}

{% block body %}
<h1 class="title">
    Welcome, {{ name }}!
</h1>

<h3 class="title">Access-rights:</h3>
Admin: {{ admin }} <br>
Campaign-Team: {{ campaign_team }} <br>
Staff: {{ staff }} <br>

{% endblock %}

flask/templates/signup.html
{% extends "base.html" %}

{% block head %}

<title>FTC Check-Your-Can Signup</title>

{% endblock %}

{% block body %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

flask/templates/wrap_up.html
{% extends "base.html" %}

{% block head %}

<title>FTC Check-Your-Can Wrap Up</title>

{% endblock %}

{% block body %}
<div class="form">
    <form action="/wrap_up" method="POST">
        <select name="mission_id" method="GET" action="/get_processed_missions" id="mission_id">
            {% for processed_mission in processed_missions %}
                <option value="{{processed_mission.id}}">{{processed_mission.pam_name}}</option>
            {% endfor %}
        </select><br>
        <input type="submit" value="View wrap up">
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
   <div class="notification is-danger">
       {{ messages[0] }}
   </div>
{% endif %}
{% endwith %}

<table>
   <thead>
      <tr>
         <th>id</th>
         <th>mission_id</th>
         <th>base_unit_name</th>
         <th>sorties</th>
         <th>pilotHealthy</th>
         <th>pilotWounded</th>
         <th>pilotDead</th>
         <th>aircraftUnharmed</th>
         <th>aircraftDamaged</th>
         <th>aircraftDestroyed</th>
         <th>pilotLossPercentage</th>
         <th>aircraftLossPercentage</th>
      </tr>
   </thead>
   
   <tbody>
      {% for wrap_up in wrap_ups %}
         <tr>
            <td>{{ wrap_up.id }}</td>
            <td>{{ wrap_up.mission_id }}</td>
            <td>{{ wrap_up.base_unit_name }}</td>
            <td>{{ wrap_up.sorties }}</td>
            <td>{{ wrap_up.pilotHealthy }}</td>
            <td>{{ wrap_up.pilotWounded }}</td>
            <td>{{ wrap_up.pilotDead }}</td>
            <td>{{ wrap_up.aircraftUnharmed }}</td>
            <td>{{ wrap_up.aircraftDamaged }}</td>
            <td>{{ wrap_up.aircraftDestroyed }}</td>
            <td>{{ wrap_up.pilotLossPercentage }}</td>
            <td>{{ wrap_up.aircraftLossPercentage }}</td>
         </tr>
      {% endfor %}
   </tbody>
</table>

{% endblock %}